{
 "title": "Mikrotik SWOS",
 "description": "Mikrotik switchos snmp monitoring",
 "tags": [
  "Mikrotik",
  "SWOS",
  "SwitchOS"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(ifHCInOctets,  instance)"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "query_result(sort(ifIndex{ifName=~'^(ether).+',instance='$instance'}) or sort(ifIndex{ifName=~'^(sfp|wlan).+',instance='$instance'}) or sort(ifIndex{ifName=~'^bridge.+',instance='$instance'}) or  sort(ifIndex{ifName!~'^(ether|bridge).+',instance='$instance'}) )"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sysDescr{instance='$instance'}", "legendFormat": "{{sysDescr}}" }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "mtxrHlProcessorTemperature{instance='$instance'}/10 or mtxrHlTemperature{instance='$instance'}/10"
    }
   ]
  },
  {
   "title": "Queue Length for all ports",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum (ifOutQLen{ifName=~'$Interface',instance='$instance'})",
     "legendFormat": "Packets"
    }
   ]
  },
  {
   "title": "Non deliverable frames",
   "type": "gauge",
   "description": "For packet-oriented interfaces, the number of packets that contained errors preventing them from being deliverable to a higher-layer protocol",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ifInErrors{ifName=~'$Interface',instance='$instance'}[20s]))",
     "legendFormat": " IN"
    },
    {
     "expr": "sum(irate(ifOutErrors{ifName=~'$Interface',instance='$instance'}[20s]))",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "Total IN Distribution",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ifInUcastPkts{ifName=~'$Interface',instance='$instance'})",
     "legendFormat": "Unicast"
    },
    {
     "expr": "sum(ifInBroadcastPkts{ifName=~'$Interface',instance='$instance'})",
     "legendFormat": "Broadcast"
    },
    {
     "expr": "sum(ifInMulticastPkts{ifName=~'$Interface',instance='$instance'})"
    },
    {
     "expr": "sum(ifInErrors{ifName=~'$Interface',instance='$instance'})"
    },
    {
     "expr": "sum(ifInDiscards{ifName=~'$Interface',instance='$instance'})"
    }
   ]
  },
  {
   "title": "Total Out Distribution",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ifOutUcastPkts{ifName=~'$Interface',instance='$instance'})",
     "legendFormat": "Unicast"
    },
    {
     "expr": "sum(ifOutBroadcastPkts{ifName=~'$Interface',instance='$instance'})",
     "legendFormat": "Broadcast"
    },
    {
     "expr": "sum(ifOutMulticastPkts{ifName=~'$Interface',instance='$instance'})"
    },
    {
     "expr": "sum(ifOutErrors{ifName=~'$Interface',instance='$instance'})"
    },
    {
     "expr": "sum(ifOutDiscards{ifName=~'$Interface',instance='$instance'})"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance='$instance'}/100"
    }
   ]
  },
  {
   "title": "SFP1 Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrOpticalTemperature{instance='$instance', mtxrOpticalIndex=\"25\"}"
    }
   ]
  },
  {
   "title": "SFP1 Voltage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrOpticalSupplyVoltage{instance='$instance', mtxrOpticalIndex=\"25\"}"
    }
   ]
  },
  {
   "title": "SFP1 Tx Bias",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrOpticalWavelength{instance='$instance', mtxrOpticalIndex=\"25\"}/10000"
    }
   ]
  },
  {
   "title": "SPF1 Traffic",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(ifInOctets{instance='$instance', ifIndex=\"25\"}[30s])*80",
     "legendFormat": "SFP1 IN"
    },
    {
     "expr": "-(irate(ifOutOctets{instance='$instance', ifIndex=\"25\"}[30s])*80)",
     "legendFormat": "SFP1 OUT"
    }
   ]
  },
  {
   "title": "SFP2 Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrOpticalTemperature{instance='$instance', mtxrOpticalIndex=\"26\"}"
    }
   ]
  },
  {
   "title": "SFP2 Voltage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrOpticalSupplyVoltage{instance='$instance', mtxrOpticalIndex=\"26\"}"
    }
   ]
  },
  {
   "title": "SFP2 Tx Bias",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrOpticalWavelength{instance='$instance', mtxrOpticalIndex=\"26\"}/10000"
    }
   ]
  },
  {
   "title": "SPF2 Traffic",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(ifInOctets{instance='$instance', ifIndex=\"26\"}[30s])*80",
     "legendFormat": "SFP1 IN"
    },
    {
     "expr": "-(irate(ifOutOctets{instance='$instance', ifIndex=\"26\"}[30s])*80)",
     "legendFormat": "SFP1 OUT"
    }
   ]
  },
  {
   "title": "All Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregated Ingress Traffic",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(ifHCInOctets{job='snmp',ifName=~'$Interface',instance='$instance'}[20s])*8",
       "legendFormat": "{{ifName}}"
      }
     ]
    },
    {
     "title": "Aggregated Engress Traffic",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(ifHCOutOctets{job='snmp',ifName=~'$Interface',instance='$instance'}[20s])*8",
       "legendFormat": "{{ifName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interface Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interface $Interface",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 0, "y": 11 },
     "repeat": "Interface",
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ifAdminStatus{ifName=~'$Interface',instance='$instance'}+500000",
       "legendFormat": "Admin"
      },
      {
       "expr": "ifOperStatus{ifName=~'$Interface',instance='$instance'}",
       "legendFormat": "Operation"
      },
      {
       "expr": "ifHighSpeed{ifName=~'$Interface',instance='$instance'}",
       "legendFormat": " Speed"
      },
      {
       "expr": "ifMtu{ifName=~'$Interface',instance='$instance'}",
       "legendFormat": "MTU"
      }
     ]
    },
    {
     "title": "Traffic on interface \"$Interface\"",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 14, "x": 2, "y": 11 },
     "repeat": "Interface",
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(ifHCInOctets{job='snmp',ifName=~'$Interface',instance='$instance'}[20s])*8",
       "legendFormat": "In"
      },
      {
       "expr": "-(irate(ifHCOutOctets{job='snmp',ifName=~'$Interface',instance='$instance'}[20s])*8)",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "IN Distribution",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 11 },
     "repeat": "Interface",
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "expr": "irate(ifInBroadcastPkts{job='snmp',ifName=~'$Interface',instance='$instance'}[20s])",
       "legendFormat": "Broadcast"
      },
      {
       "expr": "irate(ifInMulticastPkts{job='snmp',ifName=~'$Interface',instance='$instance'}[20s])",
       "legendFormat": "Multicast"
      },
      {
       "expr": "irate(ifInUcastPkts{job='snmp',ifName=~'$Interface',instance='$instance'}[20s])",
       "legendFormat": "Unicast"
      },
      {
       "expr": "irate(ifInDiscards{job='snmp',ifName=~'$Interface',instance='$instance'}[20s])",
       "legendFormat": "Discards"
      },
      {
       "expr": "irate(ifInErrors{job='snmp',ifName=~'$Interface',instance='$instance'}[20s])",
       "legendFormat": "Errors"
      }
     ]
    },
    {
     "title": "Out Distribution",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 11 },
     "repeat": "Interface",
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "expr": "irate(ifOutBroadcastPkts{job='snmp',ifName=~'$Interface',instance='$instance'}[20s])",
       "legendFormat": "Broadcast"
      },
      {
       "expr": "irate(ifOutMulticastPkts{job='snmp',ifName=~'$Interface',instance='$instance'}[20s])",
       "legendFormat": "Multicast"
      },
      {
       "expr": "irate(ifOutUcastPkts{job='snmp',ifName=~'$Interface',instance='$instance'}[20s])",
       "legendFormat": "Unicast"
      },
      {
       "expr": "irate(ifOutDiscards{job='snmp',ifName=~'$Interface',instance='$instance'}[20s])",
       "legendFormat": "Discards"
      },
      {
       "expr": "irate(ifOutErrors{job='snmp',ifName=~'$Interface',instance='$instance'}[20s])",
       "legendFormat": "Errors"
      }
     ]
    }
   ]
  }
 ]
}